/**
 * @title Debug Logger
 * @description Apply console logger exclusively in development environment
 * @param breakpointComment - Autogenerated with `lg` snippet
 */
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const logger = (breakpointComment?: string, ...args: any) => {
  // eslint-disable-next-line no-console
  console.log(breakpointComment, ...args);
};
