/**
 * @title Debug Logger
 * @description Apply console logger exclusively in development environment
 * @param breakpointComment - Autogenerated with `lg` snippet
 */

import { env } from "@/env.mjs";

// eslint-disable-next-line  @typescript-eslint/no-explicit-any
export const logger = (breakpointComment?: string, ...args: any) => {
  const isVisible: boolean = env.NEXT_PUBLIC_SHOW_LOGGER === "true" || false;
  if (!isVisible) return;
  // eslint-disable-next-line no-console
  console.log(breakpointComment, ...args);
};
